name: frame_flutter_camera
description: "Finds Frame in connected System Bluetooth Devices, initiates a photo capture and returns the image with metadata to the host app for display in a list."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  simple_frame_app:
    git: https://github.com/CitizenOneX/simple_frame_app.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/battery.min.lua
    - assets/camera.min.lua
    - assets/data.min.lua
    - assets/frame_app.min.lua